default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: root

development:
  <<: *default
  database: inv_development

# test:
#   <<: *default
#   database: inv_tests

# production:
#     <<: *default
#     adapter: postgresql
#     encoding: unicode
#     database: inv_production