default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  database: inv_development

test:
  <<: *default
  adapter: postgresql
  database: inv_test

production:
    <<: *default
    adapter: postgresql
    encoding: unicode
    database: inv_production