default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: waqarhassan

development:
  <<: *default
encoding: unicode
database: inv_development

test:
  <<: *default
database: inv_test

production:
    <<: *default
    adapter: postgresql
    encoding: unicode
    database: inv_production
